title: DEVLOG
email: cspablocortez@gmail.com
description: A devlog for the 2024 Congressional App Challenge.
baseurl: "" 
url: "https://cspablocortez.github.io" 
github_username: cspablocortez

# Build settings
theme: minima
plugins:
  - jekyll-feed
