#!/usr/bin/ruby

def time_greeting
  hour = Time.now.hour
  case hour
  when 5...12 then "Good morning!"
  when 12...18 then "Good afternoon!"
  else "Good evening!"
  end
end

welcome_message = <<~HEREDOC
  #{time_greeting}
  
  This is the command-line script for adding new 
  items to the library at cspablocortez.github.io
  
HEREDOC

puts welcome_message

library_file = '_data/library.yml'
book = {}
%w[title author url image_url release_date description].each do |attr|
  print attr + ': '
  book[attr] = gets.chomp
end

yaml_entry = <<~YAML

  - title: "#{book['title']}"
    author: "#{book['author']}"
    url: #{book['url']}
    image_url: #{book['image_url']}
    release_date: #{book['release_date']}
    description: >
      #{book['description'].gsub("\n", "\n      ")}
YAML

File.open(library_file, 'a') do |file|
  file.puts yaml_entry
end

puts "#{book['title']} was successfully added to #{library_file}"

